global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'test-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8180' ]

  - job_name: 'generate-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8182' ]

  - job_name: 'evaluate-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8190' ]

  - job_name: 'tokenize-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8184' ]

  - job_name: 'calculator-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8192' ]
